/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.frames;

import controller.ReparacionController;
import entity.Reparacion;
import java.util.List;
import javax.swing.JOptionPane;
import ui.components.ReparacionesTableDialog;

/**
 *
 * @author Carlos Ribera
 */
public class ReparacionFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReparacionFrame
     */
    public ReparacionFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarReparacionButton = new javax.swing.JButton();
        buscarReparacionButton = new javax.swing.JButton();
        listarTodasButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrarReparacionButton.setText("AÑADIR REPARACION");

        buscarReparacionButton.setText("BUSCAR REPARACION");
        buscarReparacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarReparacionButtonActionPerformed(evt);
            }
        });

        listarTodasButton.setText("LISTAR TODAS");

        jButton1.setText("ELIMINAR REPARACION");

        salirButton.setText("SALIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registrarReparacionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarReparacionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarTodasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(registrarReparacionButton)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(buscarReparacionButton)
                .addGap(18, 18, 18)
                .addComponent(listarTodasButton)
                .addGap(18, 18, 18)
                .addComponent(salirButton)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarReparacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarReparacionButtonActionPerformed
        // Muestra un input directo para que el usuario escriba el nombre o ID
        String input = JOptionPane.showInputDialog(this, "Introduce el número de teléfono del cliente");
        
        if(input != null && !input.isBlank()){
            List<Reparacion> reparacionesList = ReparacionController.findReparaciones(input);
            if(!reparacionesList.isEmpty()){
                ReparacionesTableDialog tableDialog = new ReparacionesTableDialog(this);
                tableDialog.cargarClientes(reparacionesList);
                tableDialog.setVisible(true);
            } else{
                JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
            }
        }
    }//GEN-LAST:event_buscarReparacionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReparacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReparacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReparacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReparacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReparacionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarReparacionButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton listarTodasButton;
    private javax.swing.JButton registrarReparacionButton;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
