/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.components.clientes;

import controller.ReparacionController;
import entity.Cliente;
import entity.Reparacion;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import listeners.ReparacionTableMouseListener;
import ui.components.reparaciones.CrearReparacion;
import ui.components.reparaciones.ReparacionDetallesFrame;
import utils.Utils;

/**
 *
 * @author Carlos Ribera
 */
public class ClienteReparacionesFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClienteReparacionesFrame
     */
    
    private Cliente cliente;
    private List<Reparacion> reparacionesList = new ArrayList<>();
    
    public ClienteReparacionesFrame(Cliente cliente, List<Reparacion> reparacionesList) {
        initComponents();
        this.reparacionesList = reparacionesList;
        setResizable(false);
        cargarTabla(reparacionesList);
        this.cliente = cliente;
        clienteLabel.setText(cliente.getNombre() + " " + cliente.getApellidos());
        telefonoLabel.setText(cliente.getTelefono());
        direccionLabel.setText(cliente.getDireccion());
        
    }

    private void cargarTabla(List<Reparacion> reparacionesList){
        // Crear el modelo de la tabla con las columnas
        DefaultTableModel modelo = new DefaultTableModel(new Object[][] {}, new String[] {
            "ID", "ENTRADA", "DISPOSITIVO", "REPARACION", "IMPORTE", "GARANTIA"
        }) {
        // Sobrescribir el método isCellEditable para hacer que ninguna celda sea editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Ninguna celda será editable
            }
        };    
        for(Reparacion r : reparacionesList){
            modelo.addRow(new Object[]{r.getId(),r.getFechaEntrada(), r.getModelo().getModelo(), r.getTipoReparacion().getTipoReparacion(), r.getPrecioReparacion(), r.isGarantia()});
        }
        
        // Asignar el modelo a la tabla
        reparacionesTable.setModel(modelo);
        // Oculto la columna ID
        reparacionesTable.getColumnModel().getColumn(0).setMinWidth(0);
        reparacionesTable.getColumnModel().getColumn(0).setMaxWidth(0);
        reparacionesTable.getColumnModel().getColumn(0).setWidth(0);
    
        // Agregar el MouseListener a la tabla
        reparacionesTable.addMouseListener(new ReparacionTableMouseListener(reparacionesTable, reparacionesList));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        modificarButton = new javax.swing.JButton();
        añadirButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        reparacionesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        menuClientesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPARACIONES");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Cliente:");

        clienteLabel.setText("jLabel2");

        modificarButton.setText("Modificar");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        añadirButton.setText("Añadir");
        añadirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        reparacionesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reparacionesTable.setFocusable(false);
        jScrollPane1.setViewportView(reparacionesTable);

        jLabel2.setText("REPARACIONES");

        jLabel3.setText("Teléfono:");

        telefonoLabel.setText("jLabel4");

        jLabel5.setText("Dirección:");

        direccionLabel.setText("jLabel6");

        menuClientesButton.setText("Menú Clientes");
        menuClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(modificarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(añadirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuClientesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteLabel)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(telefonoLabel)
                    .addComponent(jLabel5)
                    .addComponent(direccionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(añadirButton)
                    .addComponent(eliminarButton)
                    .addComponent(menuClientesButton)
                    .addComponent(modificarButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirButtonActionPerformed
        JFrame frame = new JFrame("Crear Reparación");
        frame.setContentPane(new CrearReparacion(cliente));
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_añadirButtonActionPerformed

    private void menuClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesButtonActionPerformed
        dispose();
    }//GEN-LAST:event_menuClientesButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        
        if(Utils.confirmationMessage("ELIMINAR", "ELIMINAR REPARACIÓN")){
             int filaSelect = reparacionesTable.getSelectedRow();
            if(filaSelect >= 0){
                int idReparacion = (int) reparacionesTable.getValueAt(filaSelect, 0);    
                if(ReparacionController.eliminarReparacion(idReparacion)){
                    JOptionPane.showMessageDialog(this, "Reparación eliminada correctamente.","ÉXITO",  JOptionPane.INFORMATION_MESSAGE); 
                    reparacionesList.clear();
                    reparacionesList = ReparacionController.findReparacionesByIdCliente(cliente.getId());
                    cargarTabla(reparacionesList);
                }
            } else{
                JOptionPane.showMessageDialog(this, "No se ha podido eliminar la reparación.","ERROR",  JOptionPane.ERROR_MESSAGE);
            }
        }   
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        int filaSelect = reparacionesTable.getSelectedRow();
        if(filaSelect >= 0){
            int idReparacion = (int) reparacionesTable.getValueAt(filaSelect, 0);
            Reparacion reparacionSelect = reparacionesList.get(filaSelect);
            
            // Crear y mostrar el dialogo de detalles de la reparación
            ReparacionDetallesFrame frame = new ReparacionDetallesFrame(reparacionSelect);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteReparacionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteReparacionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteReparacionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteReparacionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirButton;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton menuClientesButton;
    private javax.swing.JButton modificarButton;
    private javax.swing.JTable reparacionesTable;
    private javax.swing.JLabel telefonoLabel;
    // End of variables declaration//GEN-END:variables
}
