/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.components.reparaciones;

import controller.MarcaModeloController;
import controller.ReparacionController;
import controller.TipoReparacionController;
import entity.Cliente;
import entity.Marca;
import entity.Modelo;
import entity.Reparacion;
import entity.TipoReparacion;
import static java.awt.SystemColor.window;
import java.awt.Window;
import java.math.BigDecimal;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import utils.Utils;

/**
 *
 * @author Carlos Ribera
 */
public class CrearReparacion extends javax.swing.JPanel {

    /**
     * Creates new form CrearReparacion
     */
    private static Cliente cliente;
    private static Marca marcaSelect;
    private static Modelo modeloSelect;
    private static TipoReparacion tipoReparacion;
    private String fechaActual = Utils.fechaActualToString();
    ReparacionController rc = new ReparacionController();
    
    
    public CrearReparacion(Cliente cliente) {
        this.cliente = cliente;
        initComponents();

        // Establecer datos del cliente en los campos de texto
        nombreTextField.setText(cliente.getNombre().toUpperCase());
        apellidosTextField.setText(cliente.getApellidos().toUpperCase());
        telefonoTextField.setText(cliente.getTelefono().toUpperCase());
        direccionTextField.setText(cliente.getDireccion().toUpperCase());
        entradaTextField.setText(fechaActual);
        salidaTextField.setText(fechaActual);
        rc.llenarComboBoxMarca(marcaComboBox);
        rc.llenarComboBoxReparacion(tipoReparacionComboBox);
        listenerComboBoxMarca();
        listenerComboBoxModelo();   
        listenerTipoReparacionComboBox();
    }

    // Cargar Marcas disponibles en marcaComboBox
    public void listenerComboBoxMarca(){
         // Añadir el ActionListener para escuchar los cambios en la selección de marca
         marcaComboBox.addActionListener( e -> {
            // Obtengo la Marca seleccionada
            Object item = marcaComboBox.getSelectedItem();
            if(item instanceof Marca){
                marcaSelect = (Marca) item;
                int idMarca = marcaSelect.getIdMarca();
                // Cargo modeloComboBox
                rc.llenarComboBoxModelo(idMarca, modeloComboBox); 
            } else{
                // Preparo instancia para crear un nuevo tipo Modelo en la BD
                marcaSelect = new Marca();
                marcaSelect.setIdMarca(-1);
            }          
         });
    }
    
    public void listenerComboBoxModelo(){
        modeloComboBox.addActionListener( e -> {
            
            /// Obtengo el modelo seleccionado
            Object item = modeloComboBox.getSelectedItem();
            // Si se ha seleccionado un item del comboBox (No se ha añadido un modelo nuevo manualmente)
            if(item instanceof Modelo){
                modeloSelect = (Modelo) item;
            } else{
                // Preparo instancia para crear un nuevo tipo Modelo en la BD
                modeloSelect = new Modelo();
                modeloSelect.setIdModelo(-1);
            }
        });
    }
    
    public void listenerTipoReparacionComboBox(){
        tipoReparacionComboBox.addActionListener( e -> {
            tipoReparacion = (TipoReparacion) tipoReparacionComboBox.getSelectedItem();
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        nombreTextField = new javax.swing.JTextField();
        comentariosLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentariosTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apellidosTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        guardarButton = new javax.swing.JButton();
        reparacionPanel = new javax.swing.JPanel();
        marcaLabel = new javax.swing.JLabel();
        marcaComboBox = new javax.swing.JComboBox<>();
        modeloLabel = new javax.swing.JLabel();
        entradaLabel = new javax.swing.JLabel();
        entradaTextField = new javax.swing.JTextField();
        garantiaCheckBox = new javax.swing.JCheckBox();
        importeLabel = new javax.swing.JLabel();
        importeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tipoReparacionComboBox = new javax.swing.JComboBox<>();
        salidaTextField = new javax.swing.JTextField();
        salidaLabel = new javax.swing.JLabel();
        modeloComboBox = new javax.swing.JComboBox<>();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        nombreTextField.setEditable(false);

        comentariosLabel.setText("COMENTARIOS");
        comentariosLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comentariosTextArea.setColumns(20);
        comentariosTextArea.setRows(5);
        jScrollPane1.setViewportView(comentariosTextArea);

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("APELLIDOS:");

        apellidosTextField.setEditable(false);

        jLabel5.setText("TELÉFONO:");

        telefonoTextField.setEditable(false);

        jLabel6.setText("DIRECCIÓN:");

        direccionTextField.setEditable(false);

        guardarButton.setText("GUARDAR");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        marcaLabel.setText("Marca");

        marcaComboBox.setEditable(true);
        marcaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        modeloLabel.setText("Modelo");

        entradaLabel.setText("F.Entrada:");

        entradaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTextFieldActionPerformed(evt);
            }
        });

        garantiaCheckBox.setText("Garantía");
        garantiaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garantiaCheckBoxActionPerformed(evt);
            }
        });

        importeLabel.setText("Importe");

        jLabel2.setText("REPARACION:");

        tipoReparacionComboBox.setEditable(true);
        tipoReparacionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        salidaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaTextFieldActionPerformed(evt);
            }
        });

        salidaLabel.setText("F.Salida:");

        modeloComboBox.setEditable(true);
        modeloComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        javax.swing.GroupLayout reparacionPanelLayout = new javax.swing.GroupLayout(reparacionPanel);
        reparacionPanel.setLayout(reparacionPanelLayout);
        reparacionPanelLayout.setHorizontalGroup(
            reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reparacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reparacionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoReparacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(importeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(reparacionPanelLayout.createSequentialGroup()
                        .addGroup(reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entradaLabel)
                            .addComponent(marcaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entradaTextField)
                            .addComponent(marcaComboBox, 0, 130, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(reparacionPanelLayout.createSequentialGroup()
                                .addComponent(salidaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(reparacionPanelLayout.createSequentialGroup()
                                .addComponent(modeloLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modeloComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(garantiaCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        reparacionPanelLayout.setVerticalGroup(
            reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reparacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaLabel)
                    .addComponent(salidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salidaLabel)
                    .addComponent(garantiaCheckBox))
                .addGap(18, 18, 18)
                .addGroup(reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaLabel)
                    .addComponent(marcaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloLabel)
                    .addComponent(modeloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(importeLabel)
                        .addComponent(importeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reparacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tipoReparacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(reparacionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telefonoTextField)
                                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(apellidosTextField)
                                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(guardarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(comentariosLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(apellidosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reparacionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comentariosLabel)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardarButton)
                .addContainerGap(179, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void garantiaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garantiaCheckBoxActionPerformed
        
    }//GEN-LAST:event_garantiaCheckBoxActionPerformed

    private void salidaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salidaTextFieldActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        
        // Obtengo las fechas
        String fechaEntradaStr = entradaTextField.getText();
        Date fechaEntrada = Utils.stringToDate(fechaEntradaStr); 
        String fechaSalidaStr = salidaTextField.getText();
        Date fechaSalida = Utils.stringToDate(fechaSalidaStr);
        
        // Obtengo el id de la marca seleccionada
        int idMarca = marcaSelect.getIdMarca();
        // Si la marca seleccionada ha sido introducida manualmente por el USR
        if(idMarca < 1){
            System.out.println("ID NUEVA MARCA: " + idMarca);
            System.out.println("NOMBRE NUEVA MARCA: "+ marcaSelect.getMarca());
            String nuevaMarcaStr = (String) marcaComboBox.getEditor().getItem();
            marcaSelect.setMarca(nuevaMarcaStr);
            idMarca = MarcaModeloController.addMarca(marcaSelect.getMarca()); // Agrego la nueva marca a la BD y obtengo su id
        }
        
        // Obtengo el id del modelo seleccionado
        int idModelo = modeloSelect.getIdModelo();
        // Si el modelo seleccionado ha sido introducida manualmente por el USR
        if(idModelo < 1){
            idModelo = MarcaModeloController.addModelo(modeloSelect.getModelo(), idMarca); // Agrego el nuevo modelo a la BD y obtengo su id
        }
        
        // Obtengo el tipoReparación
        tipoReparacion = (TipoReparacion) tipoReparacionComboBox.getSelectedItem();
        int idTipoReparacion = tipoReparacion.getId();      
        // Si el tipo de reparación ha sido introducida manualmente por el USR
        if(idTipoReparacion < 1){
            TipoReparacionController.addTipoReparacion(tipoReparacion.getReparacion());// Agrego el nuevo tipo de reparación a la BD y obtengo su id
        }
        
        // Obtengo el importe
        String textoImporte = importeTextField.getText();
        BigDecimal importe = Utils.stringToBigDecimal(textoImporte);
        
         // Obtengo el resto de datos de la reparación
        boolean garantia = garantiaCheckBox.isSelected();
        String comentarios = comentariosTextArea.getText();
        int idCliente = cliente.getId();

        Reparacion nuevaReparacion = new Reparacion(fechaEntrada, fechaSalida, idMarca, idModelo, idTipoReparacion, importe, garantia, comentarios, idCliente);
        if (ReparacionController.crearReparacion(nuevaReparacion)) {
            JOptionPane.showMessageDialog(null, "Reparación guardada correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar la reparación.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        // Cierro el JPanel
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
}
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void entradaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaTextFieldActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosTextField;
    private javax.swing.JLabel comentariosLabel;
    private javax.swing.JTextArea comentariosTextArea;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JLabel entradaLabel;
    private javax.swing.JTextField entradaTextField;
    private javax.swing.JCheckBox garantiaCheckBox;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel importeLabel;
    private javax.swing.JTextField importeTextField;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> marcaComboBox;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JComboBox<String> modeloComboBox;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JPanel reparacionPanel;
    private javax.swing.JLabel salidaLabel;
    private javax.swing.JTextField salidaTextField;
    private javax.swing.JTextField telefonoTextField;
    private javax.swing.JComboBox<String> tipoReparacionComboBox;
    // End of variables declaration//GEN-END:variables
}
