/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.components.reparaciones;

import entity.Reparacion;
import java.math.BigDecimal;
import java.util.Date;
import utils.Utils;

/**
 *
 * @author Carlos Ribera
 */
public class ReparacionDetails extends javax.swing.JPanel {

    
    private boolean modoEdicion = false;
    /**
     * Creates new form ReparacionDetails
     */
    public ReparacionDetails() {
        initComponents();
        garantiaCheckBox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        clienteLabel = new javax.swing.JLabel();
        clienteTextField = new javax.swing.JTextField();
        entradaLabel = new javax.swing.JLabel();
        fechaEntradaTextField = new javax.swing.JTextField();
        salidaLabel = new javax.swing.JLabel();
        fechaSalidaTextField = new javax.swing.JTextField();
        marcaLabel = new javax.swing.JLabel();
        marcaTextField = new javax.swing.JTextField();
        modeloLabel = new javax.swing.JLabel();
        modeloTextField = new javax.swing.JTextField();
        reparacionLabel = new javax.swing.JLabel();
        reparacionTextField = new javax.swing.JTextField();
        importeLabel = new javax.swing.JLabel();
        importeTextField = new javax.swing.JTextField();
        garantiaCheckBox = new javax.swing.JCheckBox();
        comentariosLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentariosTextArea = new javax.swing.JTextArea();
        modificarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();

        idLabel.setText("ID:");

        idTextField.setEditable(false);

        clienteLabel.setText("Cliente:");

        clienteTextField.setEditable(false);

        entradaLabel.setText("F.Entrada:");

        fechaEntradaTextField.setEditable(false);

        salidaLabel.setText("F.Salida:");

        fechaSalidaTextField.setEditable(false);

        marcaLabel.setText("Marca:");

        marcaTextField.setEditable(false);

        modeloLabel.setText("Modelo:");

        modeloTextField.setEditable(false);

        reparacionLabel.setText("Reparacion:");

        reparacionTextField.setEditable(false);

        importeLabel.setText("Importe:");

        importeTextField.setEditable(false);

        garantiaCheckBox.setText("Garantía");
        garantiaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garantiaCheckBoxActionPerformed(evt);
            }
        });

        comentariosLabel.setText("COMENTARIOS");
        comentariosLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comentariosTextArea.setEditable(false);
        comentariosTextArea.setColumns(20);
        comentariosTextArea.setRows(5);
        jScrollPane1.setViewportView(comentariosTextArea);

        modificarButton.setText("MODIFICAR");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Teléfono:");

        jLabel2.setText("Dirección:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(clienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(direccionTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(334, 334, 334)
                                        .addComponent(comentariosLabel)
                                        .addGap(19, 363, Short.MAX_VALUE)))
                                .addGap(0, 9, Short.MAX_VALUE))))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(marcaLabel)
                            .addComponent(entradaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaEntradaTextField)
                            .addComponent(marcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salidaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaSalidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modeloLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modeloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reparacionLabel)
                            .addComponent(importeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reparacionTextField)
                            .addComponent(importeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(garantiaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(modificarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteLabel)
                    .addComponent(clienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaLabel)
                    .addComponent(fechaEntradaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salidaLabel)
                    .addComponent(idLabel)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaSalidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reparacionLabel)
                    .addComponent(reparacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marcaLabel)
                    .addComponent(marcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modeloLabel)
                        .addComponent(modeloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(importeLabel)
                        .addComponent(importeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(garantiaCheckBox)))
                .addGap(26, 26, 26)
                .addComponent(comentariosLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificarButton)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void garantiaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garantiaCheckBoxActionPerformed
        
    }//GEN-LAST:event_garantiaCheckBoxActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        if(!modoEdicion){
            modificarCampos(); // Habílita campos y texto "GUARDAR"
            modoEdicion = true;
        } else{
            guardarCampos(); // Deshabilita campos y cambia texto a "MODIFICAR"
            modoEdicion = false;
        }
    }//GEN-LAST:event_modificarButtonActionPerformed
    
    
    private void modificarCampos(){
        
        modoEdicion = true;
        if(modoEdicion){
            clienteTextField.setEditable(true);
            idTextField.setEditable(true);
            fechaEntradaTextField.setEditable(true);
            fechaSalidaTextField.setEditable(true);
            marcaTextField.setEditable(true);
            modeloTextField.setEditable(true);
            importeTextField.setEditable(true);
            garantiaCheckBox.setEnabled(true);
            reparacionTextField.setEditable(true);
            comentariosTextArea.setEditable(true);  
            modificarButton.setText("GUARDAR");
        } 
    }
    
    private void guardarCampos(){
        
        if(!modoEdicion){
            clienteTextField.setEditable(false);
            idTextField.setEditable(false);
            fechaEntradaTextField.setEditable(false);
            fechaSalidaTextField.setEditable(false);
            marcaTextField.setEditable(false);
            modeloTextField.setEditable(false);
            importeTextField.setEditable(false);
            garantiaCheckBox.setEnabled(false);
            reparacionTextField.setEditable(false);
            comentariosTextArea.setEditable(false);           
            modificarButton.setText("MODIFICAR");
        }
    }
    
    public void cargarReparaciones(Reparacion reparacion) {
        
        clienteTextField.setText(reparacion.getCliente().getNombre());
        /*telefonoTextField.setText(reparacion.get);
        direccionTextField*/
        idTextField.setText(String.valueOf(reparacion.getId()));
        fechaEntradaTextField.setText(String.valueOf(reparacion.getFechaEntrada()));
        fechaSalidaTextField.setText(String.valueOf(reparacion.getFechaEntrada()));
        marcaTextField.setText(reparacion.getMarca().getMarca());
        modeloTextField.setText(reparacion.getModelo().getModelo());
        importeTextField.setText(String.valueOf(reparacion.getPrecioReparacion()));
        garantiaCheckBox.setSelected(reparacion.isGarantia());
        reparacionTextField.setText(reparacion.getTipoReparacion().getReparacion());
        comentariosTextArea.setText(reparacion.getComentarios());
    }
    
    public void guardarReparacion(){
        int idReparacion = Integer.parseInt(idTextField.getText());
        String fechaEntradaStr =  fechaEntradaTextField.getText();
        Date fechaEntrada = Utils.stringToDate(fechaEntradaStr);
        String fechaSalidaStr = fechaSalidaTextField.getText();
        Date fechaSalida = Utils.stringToDate(fechaSalidaStr);
        String marca = marcaTextField.getText();
        String modelo = modeloTextField.getText();
        BigDecimal importe = new BigDecimal(importeTextField.getText());
        boolean garantia = garantiaCheckBox.isSelected();

        
        // Reparacion nuevaReparacion = new Reparacion(fechaEntrada, fechaSalida, idMarca, idModelo, idTipoReparacion, importe, garantia, comentarios, idCliente);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JTextField clienteTextField;
    private javax.swing.JLabel comentariosLabel;
    private javax.swing.JTextArea comentariosTextArea;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JLabel entradaLabel;
    private javax.swing.JTextField fechaEntradaTextField;
    private javax.swing.JTextField fechaSalidaTextField;
    private javax.swing.JCheckBox garantiaCheckBox;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel importeLabel;
    private javax.swing.JTextField importeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JTextField marcaTextField;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JTextField modeloTextField;
    private javax.swing.JButton modificarButton;
    private javax.swing.JLabel reparacionLabel;
    private javax.swing.JTextField reparacionTextField;
    private javax.swing.JLabel salidaLabel;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables
}
